fix: if tag curl fails, exit 1

diff --git a/.github/workflows/create-release-tag.yaml b/.github/workflows/create-release-tag.yaml
--- a/.github/workflows/create-release-tag.yaml
+++ b/.github/workflows/create-release-tag.yaml
@@ -54,7 +54,12 @@ jobs:
           fi
           echo "Creating a new tag $tag_name..."
           SHA=${{ github.event.pull_request.merge_commit_sha }}
-          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            -d "{\"ref\":\"refs/tags/$tag_name\", \"sha\":\"${{ env.SHA }}\"}" \
-            https://api.github.com/repos/${{ github.repository }}/git/refs
-          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV
+          response=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -d "{\"ref\":\"refs/tags/$tag_name\", \"sha\":\"$SHA\"}" \
+            https://api.github.com/repos/${{ github.repository }}/git/refs)
+          http_status=$(echo "$response" | jq -r .status)
+          if [ "$http_status" -ne 201 ]; then
+            echo "Failed to create tag. Status: $http_status"
+            echo "$response"
+            exit 1
+          fi
